apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-hello
    #此标签是deployment自身的标签，没有什么要求
  name: argocd-hello
  #定义deployment的名称
spec:
  replicas: 1
  #定义pod的副本数量
  selector:
    matchLabels:
      app: argocd-hello
      #此标签必须和下方定义的labels中的其中一个相同
  #上文定义的是deployment信息
  #下文定义的是Pod信息
  template:
    metadata:
      labels:
        app: argocd-hello
        #此标签必须有一个和上方定义的labels相同
        #deployment依靠此标签来找到对应的pod来监控
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ default .Values.image.tag }}"
        name: go-hello-http
        ports: 
          - containerPort: 80
